FROM java:8
LABEL maintainer="dishadhingra100@gmail.com"
VOLUME /tmp
EXPOSE 8080
ADD /target/service-2-0.0.1-SNAPSHOT.jar service-2-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","service-2-0.0.1-SNAPSHOT.jar"]