FROM java:8
LABEL maintainer="dishadhingra100@gmail.com"
VOLUME /tmp
EXPOSE 8081
ADD /target/service-1-0.0.1-SNAPSHOT.jar service-1-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","service-1-0.0.1-SNAPSHOT.jar"]